// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ravenous.Models.DbModels;

#nullable disable

namespace Ravenous.Migrations
{
    [DbContext(typeof(RavenousContext))]
    partial class RavenousContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ravenous.Models.DbModels.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("IngredientId")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.IngredientAssignment", b =>
                {
                    b.Property<int>("IngredientAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientAssignmentId"));

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasColumnName("amount");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("integer")
                        .HasColumnName("measurement_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.HasKey("IngredientAssignmentId")
                        .HasName("pk_ingredient_assignments");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_ingredient_assignments_ingredient_id");

                    b.HasIndex("MeasurementId")
                        .HasDatabaseName("ix_ingredient_assignments_measurement_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_ingredient_assignments_recipe_id");

                    b.ToTable("ingredient_assignments", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("instruction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstructionId"));

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("InstructionId")
                        .HasName("pk_instructions");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_instructions_recipe_id");

                    b.ToTable("instructions", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("measurement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("MeasurementId")
                        .HasName("pk_measurements");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<TimeOnly>("CookTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("cook_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("PrepTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("prep_time");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int?>("RecipeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_type_id");

                    b.HasKey("RecipeId")
                        .HasName("pk_recipes");

                    b.HasIndex("RecipeTypeId")
                        .HasDatabaseName("ix_recipes_recipe_type_id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.RecipeType", b =>
                {
                    b.Property<int>("RecipeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RecipeTypeId")
                        .HasName("pk_recipe_types");

                    b.ToTable("recipe_types", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.TagAssignment", b =>
                {
                    b.Property<int>("TagAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagAssignmentId"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("TagAssignmentId")
                        .HasName("pk_tag_assignments");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_tag_assignments_recipe_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_tag_assignments_tag_id");

                    b.ToTable("tag_assignments", (string)null);
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.IngredientAssignment", b =>
                {
                    b.HasOne("Ravenous.Models.DbModels.Ingredient", "Ingredient")
                        .WithMany("IngredientAssignments")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_assignments_ingredients_ingredient_id");

                    b.HasOne("Ravenous.Models.DbModels.Measurement", "Measurement")
                        .WithMany("IngredientAssignments")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_assignments_measurements_measurement_id");

                    b.HasOne("Ravenous.Models.DbModels.Recipe", "Recipe")
                        .WithMany("IngredientAssignments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_assignments_recipes_recipe_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Measurement");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Instruction", b =>
                {
                    b.HasOne("Ravenous.Models.DbModels.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instructions_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Recipe", b =>
                {
                    b.HasOne("Ravenous.Models.DbModels.RecipeType", "RecipeType")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeTypeId")
                        .HasConstraintName("fk_recipes_recipe_types_recipe_type_id");

                    b.Navigation("RecipeType");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.TagAssignment", b =>
                {
                    b.HasOne("Ravenous.Models.DbModels.Recipe", "Recipe")
                        .WithMany("TagAssignments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_assignments_recipes_recipe_id");

                    b.HasOne("Ravenous.Models.DbModels.Tag", "Tag")
                        .WithMany("TagAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_assignments_tags_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Ingredient", b =>
                {
                    b.Navigation("IngredientAssignments");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Measurement", b =>
                {
                    b.Navigation("IngredientAssignments");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Recipe", b =>
                {
                    b.Navigation("IngredientAssignments");

                    b.Navigation("Instructions");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.RecipeType", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Ravenous.Models.DbModels.Tag", b =>
                {
                    b.Navigation("TagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
